//! The pattern library (ADR 0042): patterns kept outside documents, in a folder of PNG files
//! with a small index (`index.json`: their names and order) that other apps can read, and a
//! few patterns generated by SlopShop itself. A pattern chosen for a document becomes one of
//! its sources: a document never refers to the library.
//!
//! ```json
//! { "patterns": [{ "file": "a1b2c3.png", "name": "Bricks" }] }
//! ```

use std::path::{Path, PathBuf};
use std::sync::Arc;

use serde::{Deserialize, Serialize};
use slopshop_core::color::{ChannelLayout, ColorSpace, PixelFormat, SampleType};
use slopshop_core::geom::Size;
use slopshop_core::raster::RasterImage;
use slopshop_core::{Document, Edit, Layer, LayerContent};

use slopshop_core::CancelToken;

use crate::export::{ExportFormatKind, default_spec, export_image};

/// The index file of a library folder.
const INDEX: &str = "index.json";

/// The patterns SlopShop generates, by identifier (the UI names them).
pub const BUILT_IN: [&str; 4] = ["checkers", "stripes", "dots", "noise"];

/// A pattern of the library: a generated one (`builtin:<id>`) or a file of the folder
/// (`file:<name>.png`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct PatternEntry {
    pub id: String,
    /// What the user named it; empty for a generated one (the UI names those).
    pub name: String,
}

#[derive(Debug, Default, Serialize, Deserialize)]
struct Index {
    #[serde(default)]
    patterns: Vec<IndexEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct IndexEntry {
    file: String,
    #[serde(default)]
    name: String,
}

/// A library folder.
#[derive(Debug, Clone)]
pub struct Library {
    folder: PathBuf,
}

impl Library {
    pub fn new(folder: impl Into<PathBuf>) -> Self {
        Self {
            folder: folder.into(),
        }
    }

    fn index(&self) -> Index {
        std::fs::read(self.folder.join(INDEX))
            .ok()
            .and_then(|bytes| serde_json::from_slice(&bytes).ok())
            .unwrap_or_default()
    }

    /// The generated patterns, then the folder's in their order (those whose file is gone are
    /// left out).
    pub fn list(&self) -> Vec<PatternEntry> {
        let built_in = BUILT_IN.iter().map(|id| PatternEntry {
            id: format!("builtin:{id}"),
            name: String::new(),
        });
        let files = self
            .index()
            .patterns
            .into_iter()
            .filter(|e| safe_file(&e.file) && self.folder.join(&e.file).is_file())
            .map(|e| PatternEntry {
                id: format!("file:{}", e.file),
                name: e.name,
            });
        built_in.chain(files).collect()
    }

    /// The pixels of pattern `id`.
    pub fn load(&self, id: &str) -> Result<Arc<RasterImage>, String> {
        if let Some(name) = id.strip_prefix("builtin:") {
            return built_in(name).ok_or_else(|| format!("no generated pattern {name}"));
        }
        let file = id
            .strip_prefix("file:")
            .filter(|f| safe_file(f))
            .ok_or_else(|| format!("no pattern {id}"))?;
        crate::open_image(&self.folder.join(file))
            .map(|imported| Arc::new(imported.image))
            .map_err(|e| e.to_string())
    }

    /// Add `image` to the library as `name`, last; written as PNG (8 or 16 bits as its samples,
    /// its color space kept when PNG can say it). Blocking: not on the UI thread.
    pub fn add(&self, name: &str, image: Arc<RasterImage>) -> Result<PatternEntry, String> {
        std::fs::create_dir_all(&self.folder).map_err(|e| e.to_string())?;
        let mut index = self.index();
        let file = (1u32..)
            .map(|n| format!("pattern-{n}.png"))
            .find(|f| !self.folder.join(f).exists() && index.patterns.iter().all(|e| &e.file != f))
            .ok_or("no file name left")?;
        write_png(&self.folder.join(&file), image)?;
        index.patterns.push(IndexEntry {
            file: file.clone(),
            name: name.to_owned(),
        });
        let json = serde_json::to_vec_pretty(&index).map_err(|e| e.to_string())?;
        std::fs::write(self.folder.join(INDEX), json).map_err(|e| e.to_string())?;
        Ok(PatternEntry {
            id: format!("file:{file}"),
            name: name.to_owned(),
        })
    }
}

/// A plain file name of the folder: nothing reaching elsewhere (the index is a file anyone can
/// edit).
fn safe_file(file: &str) -> bool {
    !file.is_empty()
        && Path::new(file).file_name().is_some_and(|f| f == file)
        && file.to_ascii_lowercase().ends_with(".png")
}

/// `image` written to `path` as a PNG file of its own.
fn write_png(path: &Path, image: Arc<RasterImage>) -> Result<(), String> {
    let size = image.size();
    let mut document = Document::new(size);
    let id = document.allocate_layer_id();
    Edit::InsertLayer {
        parent: None,
        index: 0,
        layer: Layer {
            id,
            name: String::new(),
            visible: true,
            opacity: 1.0,
            blend_mode: slopshop_core::BlendMode::Normal,
            content: LayerContent::raster(image),
            mask: None,
            clipped: false,
            transform: slopshop_core::Projective::IDENTITY,
            style: None,
        },
    }
    .apply(&mut document)
    .map_err(|e| e.to_string())?;
    let spec = default_spec(ExportFormatKind::Png, &document);
    export_image(
        path,
        size,
        &spec,
        |region, out| {
            slopshop_core::composite::composite_region(&document, region, out)
                .map(|report| report.non_finite)
                .map_err(|e| e.to_string())
        },
        &CancelToken::new(),
        &mut |_| {},
    )
    .map(|_| ())
    .map_err(|e| e.to_string())
}

/// A generated pattern's texel at (`x`, `y`): sRGB-encoded RGBA, straight.
type Pixel = dyn Fn(u32, u32) -> [u8; 4];

/// Generated pattern `name` (one of [`BUILT_IN`]): small, 8-bit sRGB, seamless.
pub fn built_in(name: &str) -> Option<Arc<RasterImage>> {
    let (side, pixel): (u32, Box<Pixel>) = match name {
        // Gray and white squares of 8 pixels.
        "checkers" => (
            16,
            Box::new(|x, y| {
                let v = if (x / 8 + y / 8) % 2 == 0 { 204 } else { 255 };
                [v, v, v, 255]
            }),
        ),
        // Black diagonal stripes on transparency, 4 pixels wide every 8.
        "stripes" => (
            16,
            Box::new(|x, y| [0, 0, 0, if (x + y) % 8 < 4 { 255 } else { 0 }]),
        ),
        // A black dot of radius 3 on transparency, every 12 pixels, anti-aliased.
        "dots" => (
            12,
            Box::new(|x, y| {
                let d = (f64::from(x) + 0.5 - 6.0).hypot(f64::from(y) + 0.5 - 6.0);
                [0, 0, 0, ((3.5 - d).clamp(0.0, 1.0) * 255.0).round() as u8]
            }),
        ),
        // Gray noise, the same each time.
        "noise" => (
            64,
            Box::new(|x, y| {
                let mut h = x.wrapping_mul(73_856_093) ^ y.wrapping_mul(19_349_663) ^ 0x9e37_79b9;
                h ^= h >> 13;
                h = h.wrapping_mul(0x5bd1_e995);
                h ^= h >> 15;
                let v = (h & 0xff) as u8;
                [v, v, v, 255]
            }),
        ),
        _ => return None,
    };
    let mut bytes = Vec::with_capacity((side * side * 4) as usize);
    for y in 0..side {
        for x in 0..side {
            bytes.extend(pixel(x, y));
        }
    }
    let format = PixelFormat {
        layout: ChannelLayout::Rgba,
        sample: SampleType::U8,
        color_space: ColorSpace::SRGB,
        alpha: slopshop_core::color::AlphaMode::Straight,
    };
    RasterImage::from_pixels(Size::new(side, side), format, &bytes)
        .ok()
        .map(Arc::new)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn folder(name: &str) -> PathBuf {
        let folder =
            std::env::temp_dir().join(format!("slopshop-patterns-{}-{name}", std::process::id()));
        std::fs::remove_dir_all(&folder).ok();
        folder
    }

    #[test]
    fn the_generated_patterns_are_listed_first_and_load() {
        let library = Library::new(folder("builtin"));
        let list = library.list();
        assert_eq!(
            list.iter().map(|e| e.id.as_str()).collect::<Vec<_>>(),
            [
                "builtin:checkers",
                "builtin:stripes",
                "builtin:dots",
                "builtin:noise"
            ]
        );
        for entry in &list {
            let image = library.load(&entry.id).unwrap();
            assert!(image.size().width > 0);
        }
        assert!(library.load("builtin:bricks").is_err());
    }

    #[test]
    fn a_pattern_added_is_kept_as_png_and_listed_with_its_name() {
        let path = folder("added");
        let library = Library::new(&path);
        let dots = built_in("dots").unwrap();
        let entry = library.add("Polka", Arc::clone(&dots)).unwrap();
        assert_eq!(entry.name, "Polka");
        let again = Library::new(&path);
        let listed = again.list();
        assert_eq!(listed.last(), Some(&entry));
        let back = again.load(&entry.id).unwrap();
        assert_eq!(back.size(), dots.size());
        // Pixels kept (8-bit sRGB with alpha, written as it is).
        assert_eq!(back.format(), dots.format());
        let tile = |image: &RasterImage| {
            let origin = slopshop_core::tile::TileCoord { col: 0, row: 0 };
            image.levels()[0].tile(origin).cloned()
        };
        assert_eq!(tile(&back), tile(&dots));
        // A second one does not overwrite the first.
        let second = again.add("Polka 2", dots).unwrap();
        assert_ne!(second.id, entry.id);
        assert_eq!(Library::new(&path).list().len(), BUILT_IN.len() + 2);
        std::fs::remove_dir_all(&path).ok();
    }

    #[test]
    fn an_index_naming_files_elsewhere_is_ignored() {
        let path = folder("unsafe");
        std::fs::create_dir_all(&path).unwrap();
        std::fs::write(
            path.join(INDEX),
            r#"{"patterns":[{"file":"../secret.png","name":"x"},{"file":"missing.png"}]}"#,
        )
        .unwrap();
        let library = Library::new(&path);
        assert_eq!(library.list().len(), BUILT_IN.len());
        assert!(library.load("file:../secret.png").is_err());
        std::fs::remove_dir_all(&path).ok();
    }
}
