//! What the AI installer downloads, pinned (ADR 0025). Generated by `tools/manifest.py`:
//! do not edit by hand.

use crate::install::{Component, Download, License, Source};

const ONNXRUNTIME: License = License {
    name: "MIT",
    url: "https://github.com/microsoft/onnxruntime/blob/main/LICENSE",
    commercial: true,
    accept: false,
};
const DIRECTML: License = License {
    name: "Microsoft DirectML License",
    url: "https://www.nuget.org/packages/Microsoft.AI.DirectML/1.15.4/License",
    commercial: true,
    accept: true,
};
const SAM2: License = License {
    name: "Apache-2.0",
    url: "https://github.com/facebookresearch/sam2/blob/main/LICENSE",
    commercial: true,
    accept: false,
};
const BIREFNET: License = License {
    name: "MIT",
    url: "https://github.com/ZhengPeng7/BiRefNet/blob/main/LICENSE",
    commercial: true,
    accept: false,
};
const VITMATTE: License = License {
    name: "Apache-2.0",
    url: "https://huggingface.co/hustvl/vitmatte-small-composition-1k",
    commercial: true,
    accept: false,
};

/// Every component, by id.
pub const COMPONENTS: &[Component] = &[
    Component {
        id: "runtime-directml",
        licenses: &[ONNXRUNTIME, DIRECTML],
        files: &[
            Download {
                path: "runtime/directml/onnxruntime.dll",
                url: "https://files.pythonhosted.org/packages/88/ea/33814eb0ec96775eda4c1d30b0d86e91d7d2cd0d84c66d3915aef0e06fa3/onnxruntime_directml-1.24.4-cp312-cp312-win_amd64.whl",
                source: Source::Deflated {
                    offset: 9377518,
                    compressed: 6706812,
                },
                size: 21111832,
                sha256: "302c69f9779d63ef4ab90316e59444c4acbaca7fe3455020d79d10bcfcb00715",
            },
            Download {
                path: "runtime/directml/onnxruntime_providers_shared.dll",
                url: "https://files.pythonhosted.org/packages/88/ea/33814eb0ec96775eda4c1d30b0d86e91d7d2cd0d84c66d3915aef0e06fa3/onnxruntime_directml-1.24.4-cp312-cp312-win_amd64.whl",
                source: Source::Deflated {
                    offset: 16098247,
                    compressed: 12163,
                },
                size: 21576,
                sha256: "f6bbae3af4c0673b0d1e6ca8db900dc85ad959a395b69d361038ec7995cc2652",
            },
            Download {
                path: "runtime/directml/DirectML.dll",
                url: "https://files.pythonhosted.org/packages/88/ea/33814eb0ec96775eda4c1d30b0d86e91d7d2cd0d84c66d3915aef0e06fa3/onnxruntime_directml-1.24.4-cp312-cp312-win_amd64.whl",
                source: Source::Deflated {
                    offset: 42715,
                    compressed: 9332752,
                },
                size: 18527776,
                sha256: "b73972115320e906a49602f2027a3266622881b0d325ba685e0f165a9482a8d7",
            },
        ],
    },
    Component {
        id: "sam2.1-base-plus",
        licenses: &[SAM2],
        files: &[
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/vision_encoder_fp16.onnx",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/vision_encoder_fp16.onnx",
                source: Source::File,
                size: 643078,
                sha256: "cb9324a431bfb78c70e4ead1ffb80766e236b50decd55c236c8eada4f0afde96",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/vision_encoder_fp16.onnx_data",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/vision_encoder_fp16.onnx_data",
                source: Source::File,
                size: 152780640,
                sha256: "78be422d399181ce3af00130409ebe32eb5b95825e7fe290440fbfaac70b99b4",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/prompt_encoder_mask_decoder_fp16.onnx",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/prompt_encoder_mask_decoder_fp16.onnx",
                source: Source::File,
                size: 229799,
                sha256: "3c303a6ee7359bfd56dd767f69ce46948d0ce47465ad0396281d533dca3bc422",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/prompt_encoder_mask_decoder_fp16.onnx_data",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/prompt_encoder_mask_decoder_fp16.onnx_data",
                source: Source::File,
                size: 10454016,
                sha256: "5f49783081ae45a100b62931ae02f362fd15702abf6a51e993353bc3a92618c0",
            },
        ],
    },
    Component {
        id: "vitmatte-small",
        licenses: &[VITMATTE],
        files: &[Download {
            path: "models/Xenova/vitmatte-small-composition-1k/onnx/model.onnx",
            url: "https://huggingface.co/Xenova/vitmatte-small-composition-1k/resolve/6bc1297f6140f055a227b6d2cfe8c093281f35d2/onnx/model.onnx",
            source: Source::File,
            size: 103885865,
            sha256: "bf28d2e0be2c073286e88d60ad649d7123da2749a2d99133fd1098d5887e0225",
        }],
    },
    Component {
        id: "birefnet",
        licenses: &[BIREFNET],
        files: &[Download {
            path: "models/onnx-community/BiRefNet-ONNX/onnx/model_fp16.onnx",
            url: "https://huggingface.co/onnx-community/BiRefNet-ONNX/resolve/534d3c82d3bb8b2f0867db6dfbc3a525b8e42f67/onnx/model_fp16.onnx",
            source: Source::File,
            size: 489666272,
            sha256: "3654c741eb80bd926ada8fed1713b506ccf8d30eb1f6487e87eb9f234f33df09",
        }],
    },
];
