//! What the AI installer downloads, pinned (ADR 0025). Generated by `tools/manifest.py`:
//! do not edit by hand.

use crate::install::{Component, Download, License, Source};

const ONNXRUNTIME: License = License {
    name: "MIT",
    url: "https://github.com/microsoft/onnxruntime/blob/main/LICENSE",
    commercial: true,
    accept: false,
};
const CUDA: License = License {
    name: "NVIDIA CUDA Toolkit EULA",
    url: "https://docs.nvidia.com/cuda/eula/index.html",
    commercial: true,
    accept: true,
};
const CUDNN: License = License {
    name: "NVIDIA cuDNN Software License Agreement",
    url: "https://docs.nvidia.com/deeplearning/cudnn/backend/latest/reference/eula.html",
    commercial: true,
    accept: true,
};
const SAM2: License = License {
    name: "Apache-2.0",
    url: "https://github.com/facebookresearch/sam2/blob/main/LICENSE",
    commercial: true,
    accept: false,
};

/// Every component, by id.
pub const COMPONENTS: &[Component] = &[
    Component {
        id: "runtime-cuda",
        licenses: &[ONNXRUNTIME, CUDA, CUDNN],
        files: &[
            Download {
                path: "runtime/cuda/onnxruntime.dll",
                url: "https://github.com/microsoft/onnxruntime/releases/download/v1.30.0/onnxruntime-win-x64-gpu_cuda13-1.30.0.zip",
                source: Source::Deflated {
                    offset: 218516,
                    compressed: 5943657,
                },
                size: 16921400,
                sha256: "ed0de29f6579482eb2d54674a5e51b77761e195a5e0d70dbadc916ab925a9ec1",
            },
            Download {
                path: "runtime/cuda/onnxruntime_providers_shared.dll",
                url: "https://github.com/microsoft/onnxruntime/releases/download/v1.30.0/onnxruntime-win-x64-gpu_cuda13-1.30.0.zip",
                source: Source::Deflated {
                    offset: 288501763,
                    compressed: 12369,
                },
                size: 21856,
                sha256: "7ee69db9b57ce7279fd0a3b2c2ecb262de2509faeaf48de65a73415f9a0ca6f9",
            },
            Download {
                path: "runtime/cuda/onnxruntime_providers_cuda.dll",
                url: "https://github.com/microsoft/onnxruntime/releases/download/v1.30.0/onnxruntime-win-x64-gpu_cuda13-1.30.0.zip",
                source: Source::Deflated {
                    offset: 80326483,
                    compressed: 145794384,
                },
                size: 186986848,
                sha256: "9b4e3abd26420845561c548d48adb80dde730e8d585b8f9c7a2d14cddc806eaa",
            },
            Download {
                path: "runtime/cuda/cudart64_13.dll",
                url: "https://files.pythonhosted.org/packages/86/00/d5436004268f049214193659ebc36550b5ef3925c3d13b4cc980e13be6f5/nvidia_cuda_runtime-13.4.92-py3-none-win_amd64.whl",
                source: Source::Deflated {
                    offset: 68,
                    compressed: 215509,
                },
                size: 551024,
                sha256: "d26fd1c2629594759af569a5252f94e4568d4ebeca67dc323834deb141aa278a",
            },
            Download {
                path: "runtime/cuda/cublas64_13.dll",
                url: "https://files.pythonhosted.org/packages/a3/df/f1246959833e2c437db8be3e5b477f66b87f8817821ed40de6c7561c9a36/nvidia_cublas-13.8.0.4-py3-none-win_amd64.whl",
                source: Source::Deflated {
                    offset: 68,
                    compressed: 50740237,
                },
                size: 54873200,
                sha256: "60bbba8868290311e9c1657b2193ddec667744eb555ff843f87acb7c039f9efa",
            },
            Download {
                path: "runtime/cuda/cublasLt64_13.dll",
                url: "https://files.pythonhosted.org/packages/a3/df/f1246959833e2c437db8be3e5b477f66b87f8817821ed40de6c7561c9a36/nvidia_cublas-13.8.0.4-py3-none-win_amd64.whl",
                source: Source::Deflated {
                    offset: 50740375,
                    compressed: 372350161,
                },
                size: 493474416,
                sha256: "cad63434448e7141629e240ea093ad596a7ef6a0f67b468ba9bc1df6e1eeee33",
            },
            Download {
                path: "runtime/cuda/cudnn64_9.dll",
                url: "https://files.pythonhosted.org/packages/87/6a/e55ff0ac26a5c6e2b21f41c9d04ad096b4ed6da593fba7e25845c61b0532/nvidia_cudnn_cu13-9.27.0.42-py3-none-win_amd64.whl",
                source: Source::Deflated {
                    offset: 60,
                    compressed: 121298,
                },
                size: 270448,
                sha256: "0016bd73ac9192537ae5af6a3f05814316726dad1d1da44f113f0a9ef00ae34c",
            },
            Download {
                path: "runtime/cuda/cudnn_adv64_9.dll",
                url: "https://files.pythonhosted.org/packages/87/6a/e55ff0ac26a5c6e2b21f41c9d04ad096b4ed6da593fba7e25845c61b0532/nvidia_cudnn_cu13-9.27.0.42-py3-none-win_amd64.whl",
                source: Source::Deflated {
                    offset: 121422,
                    compressed: 100399743,
                },
                size: 105226864,
                sha256: "041cab1d6439d2558b4a7073a42dd95058d0395463ffb0d37275af11ec0af8d7",
            },
            Download {
                path: "runtime/cuda/cudnn_cnn64_9.dll",
                url: "https://files.pythonhosted.org/packages/87/6a/e55ff0ac26a5c6e2b21f41c9d04ad096b4ed6da593fba7e25845c61b0532/nvidia_cudnn_cu13-9.27.0.42-py3-none-win_amd64.whl",
                source: Source::Deflated {
                    offset: 100521229,
                    compressed: 1155789,
                },
                size: 1533040,
                sha256: "7dd1bcc6d8f00ad635f6a8a2cd076faba21626f3412e13c61a6bece3f88eacb1",
            },
            Download {
                path: "runtime/cuda/cudnn_engines_precompiled64_9.dll",
                url: "https://files.pythonhosted.org/packages/87/6a/e55ff0ac26a5c6e2b21f41c9d04ad096b4ed6da593fba7e25845c61b0532/nvidia_cudnn_cu13-9.27.0.42-py3-none-win_amd64.whl",
                source: Source::Deflated {
                    offset: 101677098,
                    compressed: 198094908,
                },
                size: 231660656,
                sha256: "5d9b829228ae18594dafedf718d9612606c8ce6d199aa7151bea53e863baeefe",
            },
            Download {
                path: "runtime/cuda/cudnn_engines_runtime_compiled64_9.dll",
                url: "https://files.pythonhosted.org/packages/87/6a/e55ff0ac26a5c6e2b21f41c9d04ad096b4ed6da593fba7e25845c61b0532/nvidia_cudnn_cu13-9.27.0.42-py3-none-win_amd64.whl",
                source: Source::Deflated {
                    offset: 299772091,
                    compressed: 18924122,
                },
                size: 39266928,
                sha256: "8e65eeb0a4a3b7afa48ea3ca71c4b88e355199f85485b6fc0badcc97ebc552ef",
            },
            Download {
                path: "runtime/cuda/cudnn_engines_tensor_ir64_9.dll",
                url: "https://files.pythonhosted.org/packages/87/6a/e55ff0ac26a5c6e2b21f41c9d04ad096b4ed6da593fba7e25845c61b0532/nvidia_cudnn_cu13-9.27.0.42-py3-none-win_amd64.whl",
                source: Source::Deflated {
                    offset: 318696291,
                    compressed: 70044,
                },
                size: 156272,
                sha256: "51afb44ce4b901ccdac1434f9fc9d8d707b690f39ae1e2a6ffca98c5fd9dfa96",
            },
            Download {
                path: "runtime/cuda/cudnn_ext64_9.dll",
                url: "https://files.pythonhosted.org/packages/87/6a/e55ff0ac26a5c6e2b21f41c9d04ad096b4ed6da593fba7e25845c61b0532/nvidia_cudnn_cu13-9.27.0.42-py3-none-win_amd64.whl",
                source: Source::Deflated {
                    offset: 318766399,
                    compressed: 63256,
                },
                size: 130160,
                sha256: "a0e0e2e8e8e4678956bbef93fdccc4730bd5edf9b23d38bff49030ebba1940a6",
            },
            Download {
                path: "runtime/cuda/cudnn_graph64_9.dll",
                url: "https://files.pythonhosted.org/packages/87/6a/e55ff0ac26a5c6e2b21f41c9d04ad096b4ed6da593fba7e25845c61b0532/nvidia_cudnn_cu13-9.27.0.42-py3-none-win_amd64.whl",
                source: Source::Deflated {
                    offset: 318829721,
                    compressed: 48000207,
                },
                size: 116132464,
                sha256: "ccc90435b2fd37b5ddd6a9fa0fd053ad8f46c2dc8b0a6256ef0ebea7f3efbace",
            },
            Download {
                path: "runtime/cuda/cudnn_heuristic64_9.dll",
                url: "https://files.pythonhosted.org/packages/87/6a/e55ff0ac26a5c6e2b21f41c9d04ad096b4ed6da593fba7e25845c61b0532/nvidia_cudnn_cu13-9.27.0.42-py3-none-win_amd64.whl",
                source: Source::Deflated {
                    offset: 366829998,
                    compressed: 34324022,
                },
                size: 94795376,
                sha256: "c0439ee74a3dbec8ecf56fecbc6ac2506efcce702453e36119649545d02509c3",
            },
            Download {
                path: "runtime/cuda/cudnn_ops64_9.dll",
                url: "https://files.pythonhosted.org/packages/87/6a/e55ff0ac26a5c6e2b21f41c9d04ad096b4ed6da593fba7e25845c61b0532/nvidia_cudnn_cu13-9.27.0.42-py3-none-win_amd64.whl",
                source: Source::Deflated {
                    offset: 401154084,
                    compressed: 35208630,
                },
                size: 37462128,
                sha256: "2bd7f4122eaeccb85538c2a6f7923d7254ad77d7b7149fed0a8139f1e3cf0b07",
            },
        ],
    },
    Component {
        id: "runtime-cpu",
        licenses: &[ONNXRUNTIME],
        files: &[Download {
            path: "runtime/cpu/onnxruntime.dll",
            url: "https://github.com/microsoft/onnxruntime/releases/download/v1.30.0/onnxruntime-win-x64-1.30.0.zip",
            source: Source::Deflated {
                offset: 215476,
                compressed: 5924158,
            },
            size: 16462648,
            sha256: "7e39e2bdbba836d98071ef28620735ba36a47c554cf794585269aecc50fab0da",
        }],
    },
    Component {
        id: "sam2.1-base-plus",
        licenses: &[SAM2],
        files: &[
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/vision_encoder_fp16.onnx",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/vision_encoder_fp16.onnx",
                source: Source::File,
                size: 643078,
                sha256: "cb9324a431bfb78c70e4ead1ffb80766e236b50decd55c236c8eada4f0afde96",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/vision_encoder_fp16.onnx_data",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/vision_encoder_fp16.onnx_data",
                source: Source::File,
                size: 152780640,
                sha256: "78be422d399181ce3af00130409ebe32eb5b95825e7fe290440fbfaac70b99b4",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/prompt_encoder_mask_decoder_fp16.onnx",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/prompt_encoder_mask_decoder_fp16.onnx",
                source: Source::File,
                size: 229799,
                sha256: "3c303a6ee7359bfd56dd767f69ce46948d0ce47465ad0396281d533dca3bc422",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/prompt_encoder_mask_decoder_fp16.onnx_data",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/prompt_encoder_mask_decoder_fp16.onnx_data",
                source: Source::File,
                size: 10454016,
                sha256: "5f49783081ae45a100b62931ae02f362fd15702abf6a51e993353bc3a92618c0",
            },
        ],
    },
    Component {
        id: "sam2.1-tiny",
        licenses: &[SAM2],
        files: &[
            Download {
                path: "models/onnx-community/sam2.1-hiera-tiny-ONNX/onnx/vision_encoder.onnx",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-tiny-ONNX/resolve/814a066640debee5a91e70aa401fb8e17e030503/onnx/vision_encoder.onnx",
                source: Source::File,
                size: 354238,
                sha256: "4f30aacd3aaefbca81a0b7fe4c1fc96345570ea0a6f80ced599493d1b3be2e8c",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-tiny-ONNX/onnx/vision_encoder.onnx_data",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-tiny-ONNX/resolve/814a066640debee5a91e70aa401fb8e17e030503/onnx/vision_encoder.onnx_data",
                source: Source::File,
                size: 134084864,
                sha256: "e83df9866a5afe68ea7f0f721f18f65137fc3acbf0da1c74e946d363e09c69cc",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-tiny-ONNX/onnx/prompt_encoder_mask_decoder.onnx",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-tiny-ONNX/resolve/814a066640debee5a91e70aa401fb8e17e030503/onnx/prompt_encoder_mask_decoder.onnx",
                source: Source::File,
                size: 213114,
                sha256: "874414704c5d686db7d206a35f6e15d26563d50c8c4468fccc6739bd7e491dcf",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-tiny-ONNX/onnx/prompt_encoder_mask_decoder.onnx_data",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-tiny-ONNX/resolve/814a066640debee5a91e70aa401fb8e17e030503/onnx/prompt_encoder_mask_decoder.onnx_data",
                source: Source::File,
                size: 20958208,
                sha256: "e9874d900dd4134ed60eab1e97910327c2419e0b2954485d8fd6e7f1a1470f47",
            },
        ],
    },
];
