//! What the AI installer downloads, pinned (ADR 0025). Generated by `tools/manifest.py`:
//! do not edit by hand.

use crate::install::{Component, Download, License, Source};

const ONNXRUNTIME: License = License {
    name: "MIT",
    url: "https://github.com/microsoft/onnxruntime/blob/main/LICENSE",
    commercial: true,
    accept: false,
};
const DIRECTML: License = License {
    name: "Microsoft DirectML License",
    url: "https://www.nuget.org/packages/Microsoft.AI.DirectML/1.15.4/License",
    commercial: true,
    accept: true,
};
const SAM2: License = License {
    name: "Apache-2.0",
    url: "https://github.com/facebookresearch/sam2/blob/main/LICENSE",
    commercial: true,
    accept: false,
};
const BIREFNET: License = License {
    name: "MIT",
    url: "https://github.com/ZhengPeng7/BiRefNet/blob/main/LICENSE",
    commercial: true,
    accept: false,
};
const VITMATTE: License = License {
    name: "Apache-2.0",
    url: "https://huggingface.co/hustvl/vitmatte-small-composition-1k",
    commercial: true,
    accept: false,
};

const VITMATTE_BASE: License = License {
    name: "Apache-2.0",
    url: "https://huggingface.co/hustvl/vitmatte-base-composition-1k",
    commercial: true,
    accept: false,
};
const FLUX2_KLEIN: License = License {
    name: "Apache-2.0",
    url: "https://huggingface.co/black-forest-labs/FLUX.2-klein-4B",
    commercial: true,
    accept: false,
};
const FLUX2_KLEIN_BASE: License = License {
    name: "Apache-2.0",
    url: "https://huggingface.co/black-forest-labs/FLUX.2-klein-base-4B",
    commercial: true,
    accept: false,
};
const FAL_OBJECT_REMOVE: License = License {
    name: "Apache-2.0",
    url: "https://huggingface.co/fal/flux-2-klein-4B-object-remove-lora",
    commercial: true,
    accept: false,
};
const ERASE_V1: License = License {
    name: "Apache-2.0",
    url: "https://huggingface.co/slopshop/erase-v1",
    commercial: true,
    accept: false,
};

/// Every component, by id.
pub const COMPONENTS: &[Component] = &[
    Component {
        id: "runtime-directml",
        licenses: &[ONNXRUNTIME, DIRECTML],
        files: &[
            Download {
                path: "runtime/directml/onnxruntime.dll",
                url: "https://files.pythonhosted.org/packages/88/ea/33814eb0ec96775eda4c1d30b0d86e91d7d2cd0d84c66d3915aef0e06fa3/onnxruntime_directml-1.24.4-cp312-cp312-win_amd64.whl",
                source: Source::Deflated {
                    offset: 9377518,
                    compressed: 6706812,
                },
                size: 21111832,
                sha256: "302c69f9779d63ef4ab90316e59444c4acbaca7fe3455020d79d10bcfcb00715",
            },
            Download {
                path: "runtime/directml/onnxruntime_providers_shared.dll",
                url: "https://files.pythonhosted.org/packages/88/ea/33814eb0ec96775eda4c1d30b0d86e91d7d2cd0d84c66d3915aef0e06fa3/onnxruntime_directml-1.24.4-cp312-cp312-win_amd64.whl",
                source: Source::Deflated {
                    offset: 16098247,
                    compressed: 12163,
                },
                size: 21576,
                sha256: "f6bbae3af4c0673b0d1e6ca8db900dc85ad959a395b69d361038ec7995cc2652",
            },
            Download {
                path: "runtime/directml/DirectML.dll",
                url: "https://files.pythonhosted.org/packages/88/ea/33814eb0ec96775eda4c1d30b0d86e91d7d2cd0d84c66d3915aef0e06fa3/onnxruntime_directml-1.24.4-cp312-cp312-win_amd64.whl",
                source: Source::Deflated {
                    offset: 42715,
                    compressed: 9332752,
                },
                size: 18527776,
                sha256: "b73972115320e906a49602f2027a3266622881b0d325ba685e0f165a9482a8d7",
            },
        ],
    },
    Component {
        id: "sam2.1-base-plus",
        licenses: &[SAM2],
        files: &[
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/vision_encoder_fp16.onnx",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/vision_encoder_fp16.onnx",
                source: Source::File,
                size: 643078,
                sha256: "cb9324a431bfb78c70e4ead1ffb80766e236b50decd55c236c8eada4f0afde96",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/vision_encoder_fp16.onnx_data",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/vision_encoder_fp16.onnx_data",
                source: Source::File,
                size: 152780640,
                sha256: "78be422d399181ce3af00130409ebe32eb5b95825e7fe290440fbfaac70b99b4",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/prompt_encoder_mask_decoder_fp16.onnx",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/prompt_encoder_mask_decoder_fp16.onnx",
                source: Source::File,
                size: 229799,
                sha256: "3c303a6ee7359bfd56dd767f69ce46948d0ce47465ad0396281d533dca3bc422",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/prompt_encoder_mask_decoder_fp16.onnx_data",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/prompt_encoder_mask_decoder_fp16.onnx_data",
                source: Source::File,
                size: 10454016,
                sha256: "5f49783081ae45a100b62931ae02f362fd15702abf6a51e993353bc3a92618c0",
            },
        ],
    },
    Component {
        id: "birefnet",
        licenses: &[BIREFNET],
        files: &[Download {
            path: "models/onnx-community/BiRefNet-ONNX/onnx/model_fp16.onnx",
            url: "https://huggingface.co/onnx-community/BiRefNet-ONNX/resolve/534d3c82d3bb8b2f0867db6dfbc3a525b8e42f67/onnx/model_fp16.onnx",
            source: Source::File,
            size: 489666272,
            sha256: "3654c741eb80bd926ada8fed1713b506ccf8d30eb1f6487e87eb9f234f33df09",
        }],
    },
    Component {
        id: "runtime-coreml-macos-arm64",
        licenses: &[ONNXRUNTIME],
        files: &[Download {
            path: "runtime/coreml/libonnxruntime.dylib",
            url: "https://github.com/microsoft/onnxruntime/releases/download/v1.30.0/onnxruntime-osx-arm64-1.30.0.tgz",
            source: Source::TarGz {
                archive: 42373116,
                entry: "./onnxruntime-osx-arm64-1.30.0/lib/libonnxruntime.1.30.0.dylib",
            },
            size: 43879424,
            sha256: "bcc9110f9d638a119de2db7afb3ba9a1da8085f0cb3401e1c48ae1caf450b6fa",
        }],
    },
    Component {
        id: "sam2.1-base-plus-fp32",
        licenses: &[SAM2],
        files: &[
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/vision_encoder.onnx",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/vision_encoder.onnx",
                source: Source::File,
                size: 702836,
                sha256: "6fd992cf796e6ad5a29f3b92a127f2ce33f7f320d63c8b3f02bf3775f5f692f4",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/vision_encoder.onnx_data",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/vision_encoder.onnx_data",
                source: Source::File,
                size: 305746496,
                sha256: "f8a5f1b14d02eb7ed3b3576ad6774b8ebcfef6cc20674d5f316d6144c60a08a5",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/prompt_encoder_mask_decoder.onnx",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/prompt_encoder_mask_decoder.onnx",
                source: Source::File,
                size: 213114,
                sha256: "f39eeec20243ed1c8f2cd013812e77813d937ddbc800fa4bc703761adc7e63cd",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-base-plus-ONNX/onnx/prompt_encoder_mask_decoder.onnx_data",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-base-plus-ONNX/resolve/bab18593f44e652f04cf18b60b3690f60e8996b0/onnx/prompt_encoder_mask_decoder.onnx_data",
                source: Source::File,
                size: 20958208,
                sha256: "445cd3f72a218815db10e336f4f1c46a6eb2713a0160a85af5365134607f32a7",
            },
        ],
    },
    Component {
        id: "birefnet-fp32",
        licenses: &[BIREFNET],
        files: &[Download {
            path: "models/onnx-community/BiRefNet-ONNX/onnx/model.onnx",
            url: "https://huggingface.co/onnx-community/BiRefNet-ONNX/resolve/534d3c82d3bb8b2f0867db6dfbc3a525b8e42f67/onnx/model.onnx",
            source: Source::File,
            size: 972666916,
            sha256: "58f621f00f5d756097615970a88a791584600dcf7c45b18a0a6267535a1ebd3c",
        }],
    },
    Component {
        id: "runtime-cpu-linux-x64",
        licenses: &[ONNXRUNTIME],
        files: &[Download {
            path: "runtime/cpu-x64/libonnxruntime.so",
            url: "https://github.com/microsoft/onnxruntime/releases/download/v1.30.0/onnxruntime-linux-x64-1.30.0.tgz",
            source: Source::TarGz {
                archive: 11306877,
                entry: "onnxruntime-linux-x64-1.30.0/lib/libonnxruntime.so.1.30.0",
            },
            size: 28985152,
            sha256: "245a6f8c38127551057a1cd1ffd59f0a186a227ade4f3492dea2494eb565542e",
        }],
    },
    Component {
        id: "runtime-cpu-linux-arm64",
        licenses: &[ONNXRUNTIME],
        files: &[Download {
            path: "runtime/cpu-arm64/libonnxruntime.so",
            url: "https://github.com/microsoft/onnxruntime/releases/download/v1.30.0/onnxruntime-linux-aarch64-1.30.0.tgz",
            source: Source::TarGz {
                archive: 10269495,
                entry: "onnxruntime-linux-aarch64-1.30.0/lib/libonnxruntime.so.1.30.0",
            },
            size: 25135496,
            sha256: "64e903a43a041240fd6bcffe0ac6d4fea47ef87bf24b9d097801bd00a9612a4b",
        }],
    },
    Component {
        id: "sam2.1-tiny",
        licenses: &[SAM2],
        files: &[
            Download {
                path: "models/onnx-community/sam2.1-hiera-tiny-ONNX/onnx/vision_encoder.onnx",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-tiny-ONNX/resolve/814a066640debee5a91e70aa401fb8e17e030503/onnx/vision_encoder.onnx",
                source: Source::File,
                size: 354238,
                sha256: "4f30aacd3aaefbca81a0b7fe4c1fc96345570ea0a6f80ced599493d1b3be2e8c",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-tiny-ONNX/onnx/vision_encoder.onnx_data",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-tiny-ONNX/resolve/814a066640debee5a91e70aa401fb8e17e030503/onnx/vision_encoder.onnx_data",
                source: Source::File,
                size: 134084864,
                sha256: "e83df9866a5afe68ea7f0f721f18f65137fc3acbf0da1c74e946d363e09c69cc",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-tiny-ONNX/onnx/prompt_encoder_mask_decoder.onnx",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-tiny-ONNX/resolve/814a066640debee5a91e70aa401fb8e17e030503/onnx/prompt_encoder_mask_decoder.onnx",
                source: Source::File,
                size: 213114,
                sha256: "874414704c5d686db7d206a35f6e15d26563d50c8c4468fccc6739bd7e491dcf",
            },
            Download {
                path: "models/onnx-community/sam2.1-hiera-tiny-ONNX/onnx/prompt_encoder_mask_decoder.onnx_data",
                url: "https://huggingface.co/onnx-community/sam2.1-hiera-tiny-ONNX/resolve/814a066640debee5a91e70aa401fb8e17e030503/onnx/prompt_encoder_mask_decoder.onnx_data",
                source: Source::File,
                size: 20958208,
                sha256: "e9874d900dd4134ed60eab1e97910327c2419e0b2954485d8fd6e7f1a1470f47",
            },
        ],
    },
    Component {
        id: "birefnet-lite",
        licenses: &[BIREFNET],
        files: &[Download {
            path: "models/onnx-community/BiRefNet_lite-ONNX/onnx/model.onnx",
            url: "https://huggingface.co/onnx-community/BiRefNet_lite-ONNX/resolve/de15b22ba131738a16dff04aab8bdf8dc32e3ac1/onnx/model.onnx",
            source: Source::File,
            size: 224005088,
            sha256: "5600024376f572a557870a5eb0afb1e5961636bef4e1e22132025467d0f03333",
        }],
    },
    Component {
        id: "vitmatte-small",
        licenses: &[VITMATTE],
        files: &[Download {
            path: "models/Xenova/vitmatte-small-composition-1k/onnx/model.onnx",
            url: "https://huggingface.co/Xenova/vitmatte-small-composition-1k/resolve/6bc1297f6140f055a227b6d2cfe8c093281f35d2/onnx/model.onnx",
            source: Source::File,
            size: 103885865,
            sha256: "bf28d2e0be2c073286e88d60ad649d7123da2749a2d99133fd1098d5887e0225",
        }],
    },
    Component {
        id: "vitmatte-base",
        licenses: &[VITMATTE_BASE],
        files: &[Download {
            path: "models/Xenova/vitmatte-base-composition-1k/onnx/model.onnx",
            url: "https://huggingface.co/Xenova/vitmatte-base-composition-1k/resolve/1290b014b994e95ca1b9dd9c5f72c3b6d5b7236a/onnx/model.onnx",
            source: Source::File,
            size: 387371620,
            sha256: "f6978437f5068849bcbf49b1f4e37b90aaca5155744e9fde4e6c689f70c2b9ee",
        }],
    },
    Component {
        id: "flux2-vae",
        licenses: &[FLUX2_KLEIN],
        files: &[Download {
            path: "models/black-forest-labs/FLUX.2-klein-4B/vae/diffusion_pytorch_model.safetensors",
            url: "https://huggingface.co/black-forest-labs/FLUX.2-klein-4B/resolve/e7b7dc27f91deacad38e78976d1f2b499d76a294/vae/diffusion_pytorch_model.safetensors",
            source: Source::File,
            size: 168120878,
            sha256: "ca70d2202afe6415bdbcb8793ba8cd99fd159cfe6192381504d6c4d3036e0f04",
        }],
    },
    Component {
        id: "flux2-klein-4b",
        licenses: &[FLUX2_KLEIN],
        files: &[Download {
            path: "models/black-forest-labs/FLUX.2-klein-4B/transformer/diffusion_pytorch_model.safetensors",
            url: "https://huggingface.co/black-forest-labs/FLUX.2-klein-4B/resolve/e7b7dc27f91deacad38e78976d1f2b499d76a294/transformer/diffusion_pytorch_model.safetensors",
            source: Source::File,
            size: 7751109744,
            sha256: "9f29f9edcfdae452a653ffb51a534ca4decd389952c225724ff3b94042612a6e",
        }],
    },
    Component {
        id: "flux2-klein-base-4b",
        licenses: &[FLUX2_KLEIN_BASE],
        files: &[Download {
            path: "models/black-forest-labs/FLUX.2-klein-base-4B/transformer/diffusion_pytorch_model.safetensors",
            url: "https://huggingface.co/black-forest-labs/FLUX.2-klein-base-4B/resolve/a3b4f4849157f664bdbc776fd7453c2783562f4d/transformer/diffusion_pytorch_model.safetensors",
            source: Source::File,
            size: 7751109744,
            sha256: "e109674697ffa1a3983126e32512f5428a9442bd8df59f9c95566ee90a473bb6",
        }],
    },
    Component {
        id: "fal-object-remove",
        licenses: &[FAL_OBJECT_REMOVE],
        files: &[Download {
            path: "models/fal/flux-2-klein-4B-object-remove-lora/kDEkt5q7tDLKOpQJIVMPx_pytorch_lora_weights_comfy_converted.safetensors",
            url: "https://huggingface.co/fal/flux-2-klein-4B-object-remove-lora/resolve/0e3f58790356bf1319b263fc56b333c294b42ff7/kDEkt5q7tDLKOpQJIVMPx_pytorch_lora_weights_comfy_converted.safetensors",
            source: Source::File,
            size: 76038936,
            sha256: "dc197de62e174863f83fc4052465603f4389de7c3a78e17f3d41a1f6f11488ec",
        }],
    },
    Component {
        id: "erase-v1",
        licenses: &[ERASE_V1],
        files: &[
            Download {
                path: "models/slopshop/erase-v1/erase_v1_diffusers.safetensors",
                url: "https://huggingface.co/slopshop/erase-v1/resolve/0bb45298a0f4dde0affed10c73f8ad05ad26de48/erase_v1_diffusers.safetensors",
                source: Source::File,
                size: 192703480,
                sha256: "9e368402d994d0b62ee4f2c85aded2d7c26288db95c46456f1aeeb105e06455f",
            },
            Download {
                path: "models/slopshop/erase-v1/prompt_embeds.safetensors",
                url: "https://huggingface.co/slopshop/erase-v1/resolve/0bb45298a0f4dde0affed10c73f8ad05ad26de48/prompt_embeds.safetensors",
                source: Source::File,
                size: 7880872,
                sha256: "71be1eb20caac35c8e8f3f176316b052b2fc0ccc27b254ba921068cdd00d21bc",
            },
        ],
    },
];
